### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by MichaelHatherly** [MichaelHatherly/Documenter.jl#1]
Re: https://github.com/MichaelHatherly/Docile.jl/issues/147#issuecomment-170203238, cc @hayd

Currently just a placeholder name, though slightly "thematic". See meaning https://en.wikipedia.org/wiki/Lapidary_%28text%29.

Options for name change:

- something simple and unsurprising, i.e. `MakeDocs.jl`
- a more thematic name, but not too obscure.

**Comment by hayd** [comment]
I do like `MakeDocs.jl`... mainly as I like to remember 0 things, and remembering the name of things *and* their associated meaning is kind of annoying. Also Googleability/surprise.

> `using MakeDocs`... I wonder what that package does?

Said no-one ever.

There's no rush on this, a name change can happen any time before release :)

**Comment by MichaelHatherly** [comment]
> There's no rush on this, a name change can happen any time before release :)

:+1:

**Comment by tshort** [comment]
I like `MakeDocs.jl`, and I'd rather see the change sooner rather than later. Maybe it's worth opening a [BikeShed] issue on METADATA with whatever name you want to go with. I don't remember seeing that done before, but it might help get that part out of the way.

**Comment by MichaelHatherly** [comment]
Yes, probably worth doing that soonish.

**Comment by nalimilan** [comment]
+1 for an explicit name like MakeDocs.jl. (One could think about DocsMaker, DocsBuilder, DocsGenerator...).

**Comment by MichaelHatherly** [comment]
Another option, `Documenter.jl`.

**Comment by hayd** [comment]
`Manualfacturer.jl`

**Comment by MichaelHatherly** [comment]
> `Manualfacturer.jl`

Nice! :)

**Comment by MichaelHatherly** [comment]
I'm leaning towards `Documenter.jl` since it seems, to me at least, to be a pretty self-explanatory name and nice and simple to remember. Also matches other recent package namings such as `Maker.jl`. As far as I can tell it covers @hayd's point

> remembering the name of things and their associated meaning is kind of annoying

and doesn't squash together several words like the `Docs*` names do, which I'm not really a fan of doing if possible.

I could still get behind `Manualfacturer.jl` if I can manage to type it without making any typos.
@tkelman, was that a vote in favour of @hayd's name?

**Comment by tshort** [comment]
+1 for `Documenter.jl`.

**Comment by tkelman** [comment]
Yes because I like the pun, but it would be easy to mistype. Documenter works too.

**Comment by nalimilan** [comment]
+1 for Documenter too.

**Comment by hayd** [comment]
I was joking/not serious about Manualfacturer!

+1 for Documenter.jl.

**Comment by MichaelHatherly** [comment]
Thanks all, I'll probably rename on Sunday barring any better suggestions.
