### ISSUE TITLE
Failed to load mathjax extensions

### ISSUE THREAD

**Issue by juliohm** [MichaelHatherly/Documenter.jl#39]
I get an error message at the bottom of the webpage, it doesn't affect the website though.

![screenshot from 2016-04-16 13-00-46](https://cloud.githubusercontent.com/assets/3345261/14583329/79107f10-03d3-11e6-9557-c80e85d55ed6.png)

**Comment by MichaelHatherly** [comment]
Seeing this as well, autobold and a few other extensions have the wrong path set. Will fix shortly.

**Comment by MichaelHatherly** [comment]
e1693cbc3e8f27a15109e128d17b675845f16166 should fix this I believe.

**Comment by juliohm** [comment]
Thank you @MichaelHatherly, feel free to close the issue if the change fixes it. I will work on the documentation of my package later this weekend.
