### ISSUE TITLE
How to automatically include all docstrings from a module?

### ISSUE THREAD

**Issue by bluesmoon** [MichaelHatherly/Documenter.jl#40]
Using `Lexicon`, we could just write all docstrings from a module into a markdown file.  How do we do this with `Documenter`?  I basically want to avoid having to manually add what I want documented to `index.md` since that means every time a new function is created, it needs to also be added to that file.

**Comment by MichaelHatherly** [comment]
Yes, I've thought of adding a `{autodocs}` code block,

```markdown
    {autodocs}
    Foo
    Bar
```

which would do this (`Foo` and `Bar` are modules). It's not been implemented yet since I've not decided how the sorting and filtering of docs should behave. Input on that kind of thing would be valuable if you have any.

**Comment by bluesmoon** [comment]
yes, that would be great.  I would sort as follows:

1. Module level docs
2. Exported Types
3. Exported Constants
4. Exported Methods

And the order for each will be the order specified in the `export` list.

**Comment by MichaelHatherly** [comment]
> And the order for each will be the order specified in the `export` list.

The actual order in which bindings are exported from a module doesn't get tracked as far as I recall, so it's probably not possible to do that without reparsing source files. `names(MyMod)` returns exports sorted in alphabetical order, so that might be the best we can do. Other than that your ordering sounds good to me :+1:.

**Comment by MichaelHatherly** [comment]
An basic `{autodocs}` has been added in 268162c4350501b81bbdcf37cc4e8486b5e4ccee, which can be adjusted in future if need be. For now I'll close this.
