### ISSUE TITLE
How to build stable docs with Travis?

### ISSUE THREAD

**Issue by juliohm** [MichaelHatherly/Documenter.jl#41]
Currently I only have a `latest` folder in the `gh-pages` branch. How to generate the `stable` folder automatically?

**Comment by MichaelHatherly** [comment]
When you push a new tag to github, typically using `Pkg.tag`, then `stable` should get created.

**Comment by juliohm** [comment]
Got it, I'll start pushing tags to github, was delaying it, but now I need
the docs. Thank you, I'll close the issue when I get back to my PC. Feel
free to close it. :)

-Júlio
