### ISSUE TITLE
Security of tokens

### ISSUE THREAD

**Issue by simonbyrne** [MichaelHatherly/Documenter.jl#43]
It's probably not good to be giving Travis personal access tokens, as this gives access to a users whole account (including private repositories, ability to change/delete lots of things).

A better approach would be to use [GitHub deploy keys](https://developer.github.com/guides/managing-deploy-keys/). [Here is some code](https://gist.github.com/simonbyrne/c22830777a15957e153c220904248f40) I wrote a while back when thinking about how to do this (this uses a slightly different approach of using Travis's encrypt functionality, which requires that the Travis command line tools be installed, but it is probably easier to use your approach of pasting it in to the Travis repository settings).

**Comment by MichaelHatherly** [comment]
Thanks for the links, looks like that would be a much better approach. I was wandering whether there was a way to restrict access more thoroughly than the current method. Will investigate switching over to this in the next few days hopefully.
