### ISSUE TITLE
Reinterpret docstrings.

### ISSUE THREAD

**Issue by bicycle1885** [MichaelHatherly/Documenter.jl#48]
The current guideline of docstrings (http://julia.readthedocs.io/en/latest/manual/documentation/#documentation) recommends placing arguments and examples under `# Arguments` and `# Examples` sections, respectively. But if we splice these docstrings into a Markdown output and render it in HTML, it will result in a too exaggerated heading:
![screen shot 2016-05-11 at 19 34 29](https://cloud.githubusercontent.com/assets/905683/15178371/20b6e9da-17b0-11e6-9d0e-be03921f9bb5.png)

I think we need to reinterpret these docstrings and make them modest headings like `**Arguments:**`.

Any thoughts?

**Comment by MichaelHatherly** [comment]
Yes, we could just go with the same as https://github.com/JuliaLang/julia/pull/16299, which would probably be sufficient.

**Comment by bicycle1885** [comment]
Wow, you must have read my mind!

**Comment by MichaelHatherly** [comment]
Headers are now converted to bold in a4ebb461f3b73bf6d86d0d9d7fbed73226ac06eb.

**Comment by bicycle1885** [comment]
Thank you!

On Sat, May 14, 2016 at 6:24 AM, Michael Hatherly <notifications@github.com>
wrote:

> Headers are now converted to bold in a4ebb46
> <https://github.com/MichaelHatherly/Documenter.jl/commit/a4ebb461f3b73bf6d86d0d9d7fbed73226ac06eb>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MichaelHatherly/Documenter.jl/issues/48#issuecomment-219162863>
>



-- 
=========================================
Name : 佐藤建太(Sato Kenta)
Email : bicycle1885@gmail.com
Mobile : 090-9974-7052
=========================================
