### ISSUE TITLE
Not Finding the Docstrings?

### ISSUE THREAD

**Issue by ChrisRackauckas** [MichaelHatherly/Documenter.jl#49]
Hello, I am trying to use Documenter.jl to build the documentation for my package DifferentialEquations.jl. [My attempt can be found here and follows the guide](https://github.com/ChrisRackauckas/DifferentialEquations.jl/tree/master/docs). When I run the make.jl file, I receive the output:

```
Documenter: setting up build directory.
Documenter: copying assets to build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
 !! 32 docstrings potentially missing:
```

and then it proceeds to list every function with a docstring. The functions I put in the index.md file to test on:

```
{docs}
DifferentialEquations

{docs}
findboundary(elem,bdFlag=[])
```

Do not change in the output build in /build/index.md. This is on both a Windows and Linux machine.

**Comment by MichaelHatherly** [comment]
Hi Chris, the `{docs}` syntax needs to be inside a markdown codeblock, such as

    ```
    {docs}
    DifferentialEquations
    findboundary(elem,bdFlag=[])
    ```

or an indented codeblock rather than a fenced one. Currently in https://raw.githubusercontent.com/ChrisRackauckas/DifferentialEquations.jl/master/docs/src/index.md the `{docs}` is neither indented nor fenced. Changing that should include those two docstrings into `build/index.md`.

**Comment by ChrisRackauckas** [comment]
Yes, that worked. Thank you. Now it all seemed to build correctly, but I got a weird issue with the final product after mkdocs. For some reason, instead of taking the browser to the page when clicking on a link, it takes it to the tree structure where you can only click on index.html, and then it shows the page. I'll see if it shows up like this on the online documentation after that's done building, but it's strange the local build has this issue (on two computers with Chromium, Firefox, and Chrome).

**Comment by MichaelHatherly** [comment]
Not sure why mkdocs would be doing that. Are you using `mkdocs serve` or `mkdocs build` to view the site?

(I tried loading the package but ran into an `UndefVarError: @progress not defined` error, and so wasn't able to build the docs locally to check this.)

**Comment by ChrisRackauckas** [comment]
My bad, I wasn't serving it, I just went straight to the docs after building them. Works fine when served. I think Travis CI isn't building the docs because of a syntax error on a random file I just fixed, so it should work soon and I'll close the issue.

**Comment by ChrisRackauckas** [comment]
Locally it builds fine, but Travis is giving an error. I'll post it in full:

```

Documenter: setting up target directory.
Documenter: building documentation.
ERROR: LoadError: could not spawn `mkdocs build`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
 in anonymous at process.jl:415
 in setup_stdio at /Users/travis/julia/lib/julia/sys.dylib
 in __spawn#58__ at /Users/travis/julia/lib/julia/sys.dylib
 in run at /Users/travis/julia/lib/julia/sys.dylib
 in anonymous at /Users/travis/.julia/v0.4/Documenter/src/Documenter.jl:207
 in anonymous at /Users/travis/.julia/v0.4/Documenter/src/Documenter.jl:253
 in cd at /Users/travis/julia/lib/julia/sys.dylib
 in deploydocs at /Users/travis/.julia/v0.4/Documenter/src/Documenter.jl:249
 in include at /Users/travis/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
 in process_options at /Users/travis/julia/lib/julia/sys.dylib
 in _start at /Users/travis/julia/lib/julia/sys.dylib
while loading /Users/travis/.julia/v0.4/DifferentialEquations/docs/make.jl, in expression starting on line 6
```

**Comment by MichaelHatherly** [comment]
> switched the build to be on Linux

Yes, the path where `pip` installs `mkdocs` probably isn't being added to `PATH` correctly on OSX. I'll try investigate that when I've got a chance.

**Comment by ChrisRackauckas** [comment]
Is there a way to generate relative paths to items such as .pngs and source files in the repository?

**Comment by MichaelHatherly** [comment]
>  in the repository

Where in the repository? If it's just in the `docs/src` folder then any non-markdown files just get copied over to the `docs/build` folder and you should be able to link to them using standard markdown links.

Outside of the `docs/src` file it would be best to use absolute paths I'd think.

Perhaps have a look at the ControlSystems.jl setup, https://github.com/JuliaControl/ControlSystems.jl/tree/master/docs, that generates a bunch of plots while building the documentation. Is that the kind of thing you're looking to do?

**Comment by MichaelHatherly** [comment]
> Yes, the path where `pip` installs `mkdocs` probably isn't being added to `PATH` correctly on OSX. I'll try investigate that when I've got a chance.

7a73def67b7c4f7b111bb3c8f6e4dc85957040a5 should allow for deploying from OSX now.
