### ISSUE TITLE
Filter out documentation written elsewhere e.g. Base

### ISSUE THREAD

**Issue by hayd** [MichaelHatherly/Documenter.jl#68]
If you're extending a function and adding documentation, I suspect you only want to display the new docstring rather than it appended to to documentation from other Modules.

I suspect the rule is:

1. If documentation is defined in MyPackage use only that.
2. if no documentation is defined use whatever there is e.g. from Base.

*I think this was in the Docile rewrite branch but the api has changed since then?*

**Comment by MichaelHatherly** [comment]
Docstrings do get [filtered](https://github.com/MichaelHatherly/Documenter.jl/blob/3b76ac806c42a5580354a0c4d42ac31d8cfc020a/src/modules/Expanders.jl#L156-L157) by module, but just not by default. In the `make.jl` file setting the `modules` keyword should filter which docs get added:

```julia
makedocs(
    modules = [Foo]
)
```

This should only include the docs from `Foo` and its submodules even when they're extended from some other module.

Is this the behaviour you're looking for?

**Comment by hayd** [comment]
Looks like it, thanks! though I do think it should be the default :) (I can see how that may be non-trivial.)

**Comment by MichaelHatherly** [comment]
> though I do think it should be the default

Without knowing the modules to filter by it might be tricky, but perhaps possible, though the `generate` function in #66 will include `modules = [...]` by default, so that may be sufficient.
